name: Terraform Plan 

on:
  pull_request:
    types: [synchronize, edited, opened]
    branches: [ main ]

defaults:
  run:
    working-directory: core/

jobs:
  build:
    runs-on: self-hosted
    environment: deployment
    steps:
    - uses: actions/checkout@v4
    - name: init
      run: terraform init
    - name: plan
      run: terraform plan
