name: Merge to main

on:
  push:
    paths:
      - core/**
    branches:
      - 'main'

defaults:
  run:
    working-directory: core/

jobs:
  build:
    runs-on: self-hosted
    environment: deployment
    steps:
    - uses: actions/checkout@v4
    - name: sync config
      run: ./bin/sync_file.sh core/vault/config.hcl /data/configs/vault/config.hcl core/traefik/traefik.yaml /data/configs/traefik/traefik.yaml
    - name: init
      run: terraform init
    - name: plan
      run: terraform plan
    - name: apply
      run: terraform apply -auto-approve

