name: Deploy Services on Merge to Main 

on:
  push:
    paths:
      - services/**
    branches:
      - 'main'

defaults:
  run:
    working-directory: services/

jobs:
  build:
    runs-on: self-hosted
    environment: deployment
    steps:
    - uses: actions/checkout@v4
    - name: Retrieve secret from Vault
      uses: hashicorp/vault-action@9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b
      with:
        exportToken: true
        method: jwt
        url: http://192.168.88.101:8200
        role: github-actions 
    - name: init
      run: terraform init
    - name: plan
      run: terraform plan
    - name: apply
      run: terraform apply -auto-approve
